from .models import Character, Stats

CHARACTERS: list[Character] = [
    Character(
        id="homelander",
        name="John",
        alias="Homelander",
        faction="seven",
        is_supe=True,
        powers=["flight", "laser eyes", "super strength", "invulnerability"],
        stats=Stats(strength=99, speed=92, durability=98, intelligence=70, ruthlessness=95),
        quote="I'm the strongest man in the world.",
    ),
    Character(
        id="starlight",
        name="Annie January",
        alias="Starlight",
        faction="seven",
        is_supe=True,
        powers=["light blasts", "electricity absorption"],
        stats=Stats(strength=70, speed=75, durability=72, intelligence=78, ruthlessness=40),
        quote="The light, it has to come from somewhere.",
    ),
    Character(
        id="a-train",
        name="Reggie Franklin",
        alias="A-Train",
        faction="seven",
        is_supe=True,
        powers=["super speed"],
        stats=Stats(strength=60, speed=99, durability=55, intelligence=55, ruthlessness=60),
        quote="I'm the fastest man alive.",
    ),
    Character(
        id="queen-maeve",
        name="Maggie Shaw",
        alias="Queen Maeve",
        faction="seven",
        is_supe=True,
        powers=["super strength", "enhanced durability", "swordsmanship"],
        stats=Stats(strength=88, speed=78, durability=88, intelligence=80, ruthlessness=72),
        quote="You can't save everyone.",
    ),
    Character(
        id="black-noir",
        name="Black Noir",
        alias="Black Noir",
        faction="seven",
        is_supe=True,
        powers=["stealth", "martial arts", "enhanced reflexes"],
        stats=Stats(strength=82, speed=88, durability=80, intelligence=85, ruthlessness=90),
        quote="...",
    ),
    Character(
        id="the-deep",
        name="Kevin Moskowitz",
        alias="The Deep",
        faction="seven",
        is_supe=True,
        powers=["aquatic communication", "underwater breathing"],
        stats=Stats(strength=55, speed=50, durability=50, intelligence=35, ruthlessness=30),
        quote="I talk to fish.",
    ),
    Character(
        id="stormfront",
        name="Klara Risinger",
        alias="Stormfront",
        faction="seven",
        is_supe=True,
        powers=["lightning", "flight", "longevity"],
        stats=Stats(strength=85, speed=80, durability=80, intelligence=82, ruthlessness=98),
        quote="People love what I have to say.",
    ),
    Character(
        id="butcher",
        name="Billy Butcher",
        alias="Butcher",
        faction="boys",
        is_supe=False,
        powers=["tactics", "manipulation", "brutal combat"],
        stats=Stats(strength=70, speed=68, durability=70, intelligence=85, ruthlessness=98),
        quote="Diabolical.",
    ),
    Character(
        id="hughie",
        name="Hughie Campbell",
        alias="Wee Hughie",
        faction="boys",
        is_supe=False,
        powers=["resourcefulness", "moral compass"],
        stats=Stats(strength=40, speed=55, durability=45, intelligence=78, ruthlessness=45),
        quote="Cunts.",
    ),
    Character(
        id="mm",
        name="Marvin Milk",
        alias="Mother's Milk",
        faction="boys",
        is_supe=False,
        powers=["strategy", "field medicine", "combat training"],
        stats=Stats(strength=72, speed=65, durability=70, intelligence=82, ruthlessness=70),
        quote="We do this clean.",
    ),
    Character(
        id="frenchie",
        name="Serge",
        alias="Frenchie",
        faction="boys",
        is_supe=False,
        powers=["explosives", "weapons engineering", "improvisation"],
        stats=Stats(strength=58, speed=70, durability=55, intelligence=88, ruthlessness=72),
        quote="Mon coeur.",
    ),
    Character(
        id="kimiko",
        name="Kimiko Miyashiro",
        alias="The Female",
        faction="boys",
        is_supe=True,
        powers=["super strength", "regeneration", "silent combat"],
        stats=Stats(strength=88, speed=82, durability=92, intelligence=70, ruthlessness=85),
        quote="...",
    ),
    Character(
        id="soldier-boy",
        name="Ben",
        alias="Soldier Boy",
        faction="vought",
        is_supe=True,
        powers=["super strength", "energy blast", "longevity"],
        stats=Stats(strength=95, speed=78, durability=94, intelligence=65, ruthlessness=92),
        quote="Get the f*** out of here.",
    ),
    Character(
        id="ryan",
        name="Ryan Butcher",
        alias="Ryan",
        faction="neutral",
        is_supe=True,
        powers=["super strength", "flight", "laser eyes"],
        stats=Stats(strength=80, speed=75, durability=85, intelligence=65, ruthlessness=50),
        quote="Mom said powers were a sin.",
    ),
]

BY_ID = {c.id: c for c in CHARACTERS}
